### ISSUE TITLE
dra-evolution: "constraints" vs. "requirements"

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/wg-device-management#16]
https://github.com/kubernetes-sigs/wg-device-management/pull/14 introduced different concepts:
- constraints for a set of devices
- requirements for a single device

There were concerns that this is artificial and that the naming isn't obvious. See https://github.com/kubernetes-sigs/wg-device-management/pull/14#discussion_r1618028161. Needs further discussion.

**Comment by johnbelamaric** [comment]
Personally I am leaning towards `selectors` and `constraints`. See https://github.com/kubernetes/enhancements/pull/4709#discussion_r1633637731 and https://github.com/kubernetes/enhancements/pull/4709#discussion_r1633680405.

**Comment by pohly** [comment]
I like that and the KEP update is using it now.
